class AppIcons {
  static const baseUrl = "assets/icons/";
  static const advance_ia = "${baseUrl}advance_ia.svg";
  static const learn_about_plant = "${baseUrl}learn_about_plant.svg";
  static const identify_plants = "${baseUrl}identify_plants.svg";
  static const get_care_reminders = "${baseUrl}get_care_reminders.svg";
  static const beginner_im = "${baseUrl}beginner_im.svg";
  static const choose_the_right = "${baseUrl}choose_the_right.svg";
  static const identify_mushrooms = "${baseUrl}identify_mushrooms.svg";
  static const identify_plant = "${baseUrl}identify_plant.svg";
  static const intermediate = "${baseUrl}intermediate.svg";
  static const keep_them_alive = "${baseUrl}keep_them_alive.svg";
  static const diagnose_plants = "${baseUrl}diagnose_plants.svg";
  static const managing_pests = "${baseUrl}managing_pests.svg";
  static const remembering_water = "${baseUrl}remembering_water.svg";
  static const right_care = "${baseUrl}right_care.svg";
  static const care_calender = "${baseUrl}care_calender.svg";
  static const tips_and_tricks = "${baseUrl}tips_and_tricks.svg";
  static const plant_related = "${baseUrl}plant_related.svg";
  static const new_features = "${baseUrl}new_features.svg";
  static const home_logo = "${baseUrl}home_logo.svg";
  static const pro_icon_white = "${baseUrl}pro_icon_white.svg";
  static const setting = "${baseUrl}setting.svg";
  static const camera_icon = "${baseUrl}camera_icon.svg";
  static const galery = "${baseUrl}gallery.svg";
  static const refresh = "${baseUrl}refresh.svg";
  static const send_icon = "${baseUrl}send_icon.svg";
  static const watering = "${baseUrl}watering.svg";
  static const misting = "${baseUrl}misting.svg";
  static const rotating = "${baseUrl}contrast.svg";
  static const clock = "${baseUrl}clock.svg";
  static const delete_icon = "${baseUrl}delete_icon.svg";
  static const alarm_icon = "${baseUrl}alarm_icon.svg";
  static const edit_icon = "${baseUrl}edit_icon.svg";
  static const privacy = "${baseUrl}privacy.svg";
  static const rate = "${baseUrl}rate.svg";
  static const terms = "${baseUrl}terms.svg";
  static const share = "${baseUrl}share.svg";
  static const common_problem = "${baseUrl}common_problem.svg";
  static const care_tips = "${baseUrl}care_tips.svg";
  static const treatment = "${baseUrl}treatment.svg";
  static const temperature = "${baseUrl}temperature.svg";
  static const pests = "${baseUrl}pests.svg";
  static const reporting = "${baseUrl}reporting.svg";
  static const sunlight_identify_result =
      "${baseUrl}sunlight_identify_result.svg";
  static const watering_identify_result =
      "${baseUrl}watering_identify_result.svg";
}
